version: '3.3'
services:
  database:
    image: mysql:5-debian
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "nestjs"
    restart: always
    ports:
      - "3306:3306"
